Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    #  v.cpus = 2
  end
  
  config.vm.box = "hashicorp/precise32"
  config.vm.provision :shell, path: "bootstrap.sh"
  # apache on virtual host port 80, localhost:8080
  config.vm.network :forwarded_port, host: 8080, guest: 80
  # tomcat on virtual host port 8080, localhost:9090
  config.vm.network :forwarded_port, host: 9090, guest: 8080
  config.vm.network :forwarded_port, host: 10000, guest: 10000
  config.vm.network :forwarded_port, host: 10001, guest: 10001
  config.vm.hostname = "Latte-VM"
  config.vm.provision :shell, path: "installStudentDashboard.sh", run: "always"
end
